language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t hakhundov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hakhundov/docker-react npm run test


#    DockerReact-env.eba-xyyqvxkj.us-west-2.elasticbeanstalk.com
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-949358763164"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY