language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t hakhundov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hakhundov/docker-react npm run test